# ExcelEngine.py
import os
from datetime import datetime
import openpyxl
from openpyxl.styles import (
    PatternFill, Font, Alignment, Border, Side
)
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.utils import get_column_letter
from langchain_core.tools import tool

# ─── COLORS ───────────────────────────────────────────────────────────────────
NAVY     = "1a1f2e"
AMBER    = "F0A500"
BLUE     = "00D4FF"
WHITE    = "FFFFFF"
RED      = "FF4444"
GREEN    = "00C851"
GRAY     = "2d3347"
DARKGRAY = "1e2335"

# ─── STYLE HELPERS ────────────────────────────────────────────────────────────
def header_style(ws, row, col, value, bg=NAVY, fg=AMBER, bold=True, size=12):
    cell = ws.cell(row=row, column=col, value=value)
    cell.fill = PatternFill("solid", fgColor=bg)
    cell.font = Font(color=fg, bold=bold, size=size)
    cell.alignment = Alignment(horizontal="center", vertical="center")
    return cell

def data_style(ws, row, col, value, bg=DARKGRAY, fg=WHITE, bold=False):
    cell = ws.cell(row=row, column=col, value=value)
    cell.fill = PatternFill("solid", fgColor=bg)
    cell.font = Font(color=fg, bold=bold)
    cell.alignment = Alignment(horizontal="left", vertical="center")
    return cell

def metric_style(ws, row, col, value, good=True):
    color = GREEN if good else RED
    cell = ws.cell(row=row, column=col, value=value)
    cell.fill = PatternFill("solid", fgColor=DARKGRAY)
    cell.font = Font(color=color, bold=True)
    cell.alignment = Alignment(horizontal="center", vertical="center")
    return cell

def set_col_widths(ws, widths: dict):
    for col_letter, width in widths.items():
        ws.column_dimensions[col_letter].width = width

def thin_border():
    side = Side(style="thin", color=AMBER)
    return Border(left=side, right=side, top=side, bottom=side)


# ─── SHEET BUILDERS ───────────────────────────────────────────────────────────

def build_overview_sheet(ws, company_name: str, doc_type: str, score: int, verdict: str):
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 50

    header_style(ws, 1, 1, f"REIA — Financial Report: {company_name}", size=16)
    ws.merge_cells("A1:B1")

    data_style(ws, 3, 1, "Report Date")
    data_style(ws, 3, 2, datetime.now().strftime("%d %B %Y"))

    data_style(ws, 4, 1, "Document Type")
    data_style(ws, 4, 2, doc_type.upper())

    data_style(ws, 5, 1, "Overall Score")
    metric_style(ws, 5, 2, f"{score}/100", good=score >= 50)

    data_style(ws, 6, 1, "Verdict")
    data_style(ws, 6, 2, verdict)

    data_style(ws, 8, 1, "Generated By")
    data_style(ws, 8, 2, "Reia — Your Personal AI Financial Analyst")


def build_ratios_sheet(ws, ratios: dict):
    ws.sheet_view.showGridLines = False
    set_col_widths(ws, {"A": 30, "B": 20, "C": 20, "D": 30})

    header_style(ws, 1, 1, "RATIO")
    header_style(ws, 1, 2, "VALUE")
    header_style(ws, 1, 3, "BENCHMARK")
    header_style(ws, 1, 4, "STATUS")
    ws.merge_cells("A1:D1") if False else None

    benchmarks = {
        "Current Ratio":        (1.5,  "≥ 1.5 is healthy"),
        "Quick Ratio":          (1.0,  "≥ 1.0 is safe"),
        "D/E Ratio":            (2.0,  "≤ 2.0 is acceptable"),
        "ROE":                  (0.15, "≥ 15% is strong"),
        "ROA":                  (0.05, "≥ 5% is good"),
        "Gross Margin":         (0.30, "≥ 30% is healthy"),
        "Net Margin":           (0.10, "≥ 10% is good"),
        "Interest Coverage":    (3.0,  "≥ 3x is safe"),
    }

    row = 2
    for ratio_name, value in ratios.items():
        bench = benchmarks.get(ratio_name, (None, "—"))
        data_style(ws, row, 1, ratio_name)
        data_style(ws, row, 2, value)
        data_style(ws, row, 3, bench[1])

        if bench[0]:
            good = value >= bench[0] if ratio_name != "D/E Ratio" else value <= bench[0]
            metric_style(ws, row, 4, "✅ Good" if good else "❌ Risk", good=good)
        else:
            data_style(ws, row, 4, "—")
        row += 1

    # Bar chart
    chart = BarChart()
    chart.title = "Financial Ratios"
    chart.style = 10
    chart.height = 12
    chart.width = 20

    data_ref = Reference(ws, min_col=2, min_row=2, max_row=row - 1)
    cats_ref = Reference(ws, min_col=1, min_row=2, max_row=row - 1)
    chart.add_data(data_ref, titles_from_data=False)
    chart.set_categories(cats_ref)
    ws.add_chart(chart, "F2")


def build_verdict_sheet(ws, positives: list, negatives: list, insights: list):
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 80

    header_style(ws, 1, 1, "SECTION 1 — POSITIVES", bg=GREEN, fg=WHITE, size=13)
    row = 2
    for p in positives:
        data_style(ws, row, 1, f"✅ {p}", bg=DARKGRAY, fg=WHITE)
        row += 1

    row += 1
    header_style(ws, row, 1, "SECTION 2 — NEGATIVES (WORST FIRST)", bg=RED, fg=WHITE, size=13)
    row += 1
    for n in negatives:
        data_style(ws, row, 1, f"❌ {n}", bg=DARKGRAY, fg=WHITE)
        row += 1

    row += 1
    header_style(ws, row, 1, "SECTION 3 — INSIGHTS SUMMARY", bg=NAVY, fg=AMBER, size=13)
    row += 1
    for i in insights:
        data_style(ws, row, 1, f"💡 {i}", bg=DARKGRAY, fg=WHITE)
        row += 1


def build_action_plan_sheet(ws, actions: list):
    ws.sheet_view.showGridLines = False
    set_col_widths(ws, {"A": 5, "B": 50, "C": 20, "D": 20})

    header_style(ws, 1, 1, "#")
    header_style(ws, 1, 2, "ACTION ITEM")
    header_style(ws, 1, 3, "PRIORITY")
    header_style(ws, 1, 4, "TIMELINE")

    priority_colors = {"High": RED, "Medium": AMBER, "Low": GREEN}

    for i, action in enumerate(actions, start=2):
        data_style(ws, i, 1, i - 1)
        data_style(ws, i, 2, action.get("action", ""))
        priority = action.get("priority", "Medium")
        color = priority_colors.get(priority, AMBER)
        cell = ws.cell(row=i, column=3, value=priority)
        cell.fill = PatternFill("solid", fgColor=color)
        cell.font = Font(color=WHITE, bold=True)
        data_style(ws, i, 4, action.get("timeline", "30 days"))


# ─── MAIN EXCEL GENERATOR ─────────────────────────────────────────────────────

def generate_excel_report(
    company_name: str,
    doc_type: str,
    ratios: dict,
    positives: list,
    negatives: list,
    insights: list,
    actions: list,
    score: int,
    verdict: str,
    output_dir: str = "reports"
) -> str:

    os.makedirs(output_dir, exist_ok=True)
    filename = f"{output_dir}/{company_name}_Reia_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx"

    wb = openpyxl.Workbook()
    wb.remove(wb.active)  # remove default sheet

    # Build all sheets
    build_overview_sheet(wb.create_sheet("Overview"), company_name, doc_type, score, verdict)
    build_ratios_sheet(wb.create_sheet("Ratios Dashboard"), ratios)
    build_verdict_sheet(wb.create_sheet("Final Verdict"), positives, negatives, insights)
    build_action_plan_sheet(wb.create_sheet("Action Plan"), actions)

    wb.save(filename)
    return filename


# ─── LANGCHAIN TOOL ───────────────────────────────────────────────────────────
@tool
def create_excel_report(
    company_name: str,
    ratios: dict,
    positives: list,
    negatives: list,
    insights: list,
    score: int,
    verdict: str
) -> str:
    """Generate a multi-sheet Excel financial report for a company."""
    try:
        actions = [
            {"action": neg, "priority": "High", "timeline": "30 days"}
            for neg in negatives[:3]
        ]
        path = generate_excel_report(
            company_name=company_name,
            doc_type="Financial Statement",
            ratios=ratios,
            positives=positives,
            negatives=negatives,
            insights=insights,
            actions=actions,
            score=score,
            verdict=verdict,
        )
        return f"✅ Excel report saved: {path}"
    except Exception as e:
        return f"Excel generation error: {str(e)}"




